# Generated by Django 3.0.3 on 2020-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRM_Statistics',
            fields=[
                ('semester', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('passes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kevon_Shakespeare_CRM_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kevon_Shakespeare_LinearAlgebra_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kevon_Shakespeare_Previous_Modules',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marvel_Maxwell_COA_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marvel_Maxwell_CRM_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marvel_Maxwell_LinearAlgebra_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marvel_Maxwell_Previous_Modules',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nicholas_Pinnock_COA_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nicholas_Pinnock_CRM_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nicholas_Pinnock_LinearAlgebra_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nicholas_Pinnock_Previous_Modules',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rojay_Beharie_COA_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rojay_Beharie_CRM_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rojay_Beharie_LinearAlgebra_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rojay_Beharie_Previous_Modules',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
    ]
