# Generated by Django 3.0.3 on 2020-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studDashbrd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kevon_Shakespeare_COA_grades',
            fields=[
                ('assesment', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gradePercentage', models.IntegerField()),
            ],
        ),
    ]
