# Generated by Django 3.0.3 on 2020-06-14 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studDashbrd', '0002_kevon_shakespeare_coa_grades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CRM_Statistics',
        ),
        migrations.DeleteModel(
            name='Kevon_Shakespeare_COA_grades',
        ),
        migrations.DeleteModel(
            name='Kevon_Shakespeare_CRM_grades',
        ),
        migrations.DeleteModel(
            name='Kevon_Shakespeare_LinearAlgebra_grades',
        ),
        migrations.DeleteModel(
            name='Kevon_Shakespeare_Previous_Modules',
        ),
        migrations.DeleteModel(
            name='Marvel_Maxwell_COA_grades',
        ),
        migrations.DeleteModel(
            name='Marvel_Maxwell_CRM_grades',
        ),
        migrations.DeleteModel(
            name='Marvel_Maxwell_LinearAlgebra_grades',
        ),
        migrations.DeleteModel(
            name='Marvel_Maxwell_Previous_Modules',
        ),
        migrations.DeleteModel(
            name='Nicholas_Pinnock_COA_grades',
        ),
        migrations.DeleteModel(
            name='Nicholas_Pinnock_CRM_grades',
        ),
        migrations.DeleteModel(
            name='Nicholas_Pinnock_LinearAlgebra_grades',
        ),
        migrations.DeleteModel(
            name='Nicholas_Pinnock_Previous_Modules',
        ),
        migrations.DeleteModel(
            name='Rojay_Beharie_COA_grades',
        ),
        migrations.DeleteModel(
            name='Rojay_Beharie_LinearAlgebra_grades',
        ),
        migrations.DeleteModel(
            name='Rojay_Beharie_Previous_Modules',
        ),
    ]
