# Generated by Django 3.0.3 on 2020-06-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='David_Wright_CRM_Class',
            fields=[
                ('student', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('test1', models.IntegerField()),
                ('test2', models.IntegerField()),
            ],
        ),
    ]
